name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Building project and running tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v
    - uses: actions/setup-node@v1
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
