name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
    - uses: actions/setup-node@v1
    
    - name: Install
    - run: npm ci
    
    - name: Build
    - run: npm run build
    
    - name: Run tests
    - run: npm test
