name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Building project and running tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js
      uses: actions/setup-node@v1
    - name: Installing
      run: npm ci
    - name: Building
      run: npm run build
    - name: Running tests
      run: npm run test
