name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Building project and running tests
    runs-on: ubuntu-latest

    steps:
    - name: Checking-out repository
      uses: actions/checkout@v2
    - name: Using Node.js
      uses: actions/setup-node@v1
    - name: Installing dependencies
      run: npm ci
    - name: Building project
      run: npm run build
    - name: Running tests
      run: npm run test
